name: Run all Tests

on:
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      #Run all tests from test foloder

      - name: Run all tests
        run: |
          npm install
          npm run test

      - name: Upload test report
        uses: actions/upload-artifact@v2

