name: Run all Tests

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
       node-version: '18'

      #Run all tests and print report
    - name: Run all tests
      run: |
          npm install
          npm run Tdd-Spring-Project/src/test/java/com/example/tddspringproject/model/BilTest.java
