name: Run all Tests

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup jdk
        uses: actions/setup-java@v3
        with:
          java-version: 17

      #Run all tests and print report
      - name: Run all tests
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v2
