name: Run all Tests

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
       node-version: '18'

      #Run all tests and print report
    - name: Run all test
      run: ./gradlew test

    - name: Upload test report
      uses: actions/upload-artifact@v2
